"""add columns mime type and lenngth for table file_content

Revision ID: b0e256071ca3
Revises: 014ea98c7b53
Create Date: 2023-09-04 14:42:46.980056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e256071ca3'
down_revision = '014ea98c7b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_mime_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_content_length', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_content', schema=None) as batch_op:
        batch_op.drop_column('file_content_length')
        batch_op.drop_column('file_mime_type')

    # ### end Alembic commands ###
